# Generated by Django 5.0.6 on 2024-05-12 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('M', 'mobile'), ('L', 'Laptop'), ('TW', 'Top wear'), ('BW', 'Bottom Wear')], max_length=10)),
                ('product_image', models.ImageField(upload_to='productImg')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Dhaka', 'Gulshan'), ('Chittagong', 'Khulshi'), ('Sylhet', 'Amberkhana'), ('Rajshahi', 'Shaheb Bazar'), ('Khulna', 'Sonadanga'), ('Barisal', 'Natun Bazar'), ('Comilla', 'Kandirpar'), ('Rangpur', 'Station Road'), ('Mymensingh', 'Choto Bazar'), ('Narayanganj', 'Fatullah'), ('Gazipur', 'Tongi'), ('Jessore', 'Chowmuhani'), ('Bogra', 'Satmatha'), ('Dinajpur', 'Chirirbandar'), ('Coxs Bazar', 'Kolatoli'), ('Tangail', 'Bazar Road'), ('Narsingdi', 'Ghorashal'), ('Faridpur', 'Goalchamot'), ('Pabna', 'Ishwardi'), ('Jamalpur', 'Kumarpara')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Dhaka', 'Gulshan'), ('Chittagong', 'Khulshi'), ('Sylhet', 'Amberkhana'), ('Rajshahi', 'Shaheb Bazar'), ('Khulna', 'Sonadanga'), ('Barisal', 'Natun Bazar'), ('Comilla', 'Kandirpar'), ('Rangpur', 'Station Road'), ('Mymensingh', 'Choto Bazar'), ('Narayanganj', 'Fatullah'), ('Gazipur', 'Tongi'), ('Jessore', 'Chowmuhani'), ('Bogra', 'Satmatha'), ('Dinajpur', 'Chirirbandar'), ('Coxs Bazar', 'Kolatoli'), ('Tangail', 'Bazar Road'), ('Narsingdi', 'Ghorashal'), ('Faridpur', 'Goalchamot'), ('Pabna', 'Ishwardi'), ('Jamalpur', 'Kumarpara')], default='pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
